version: '3.8'

services:
  db:
    image: postgres:15   # use latest stable PostgreSQL
    environment:
      POSTGRES_DB: librarydb
      POSTGRES_USER: libraryapp
      POSTGRES_PASSWORD: libraryapppwd
    ports:
      - "5432:5432"  # map to host for local access, optional
    volumes:
      - db_data:/var/lib/postgresql/data


  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      # Match these with application.properties below!
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/librarydb
      SPRING_DATASOURCE_USERNAME: libraryapp
      SPRING_DATASOURCE_PASSWORD: libraryapppwd
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: unless-stopped


volumes:
  db_data:
